import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-white">
      <Header />
      <section className="py-24 bg-gradient-to-b from-mint-light/30 to-white">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">Terms of Service</h1>
          <p className="text-gray-500 mb-12">Last updated: June 2026</p>

          <div className="prose prose-lg max-w-none text-gray-700 space-y-8">
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using Talk2Nebiah, you agree to be bound by these Terms of Service. If you do not agree, please do not use our services.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">2. Description of Service</h2>
              <p>Talk2Nebiah provides an AI-powered mental health support platform accessible via WhatsApp. Our AI assistant, Nebiah, offers compassionate conversations and emotional support but is not a substitute for professional mental health care.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">3. User Responsibilities</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>You must be at least 18 years old to use our services.</li>
                <li>You agree to provide accurate information when making payments.</li>
                <li>You are responsible for maintaining the confidentiality of your auth token.</li>
                <li>You agree not to misuse the platform for any unlawful purpose.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">4. Payments and Refunds</h2>
              <p>Payments are processed securely through Paystack. All prices are displayed in Naira (NGN) or US Dollars (USD). Refund requests are handled on a case-by-case basis. Please contact <a href="mailto:info@talk2nebiah.com" className="text-mint hover:underline">info@talk2nebiah.com</a> for refund inquiries.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">5. Limitation of Liability</h2>
              <p>Talk2Nebiah is provided "as is" without warranties of any kind. We are not liable for damages arising from your use of the platform. Our AI responses are generated by machine learning models and may not always be accurate or appropriate.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">6. Termination</h2>
              <p>We reserve the right to suspend or terminate your access to our services at any time, with or without cause, including violation of these terms.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">7. Contact</h2>
              <p>For questions about these terms, contact us at <a href="mailto:info@talk2nebiah.com" className="text-mint hover:underline">info@talk2nebiah.com</a>.</p>
            </section>
          </div>
        </div>
      </section>
      <Footer />
    </main>
  );
}
