import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-white">
      <Header />
      <section className="py-24 bg-gradient-to-b from-mint-light/30 to-white">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">Disclaimer</h1>
          <p className="text-gray-500 mb-12">Last updated: June 2026</p>

          <div className="prose prose-lg max-w-none text-gray-700 space-y-8">
            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">Not a Medical Service</h2>
              <p>Talk2Nebiah provides AI-powered conversational support and is <strong>not a medical or therapeutic service</strong>. Nebiah is an artificial intelligence assistant, not a licensed mental health professional, therapist, psychiatrist, or counselor.</p>
              <p className="mt-4">Our service does not diagnose, treat, cure, or prevent any mental health condition. It is intended as a supplementary tool for emotional support and should not replace professional medical advice, diagnosis, or treatment.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">Emergency Situations</h2>
              <p className="font-semibold text-red-600">If you are in crisis or experiencing a medical emergency, please call your local emergency services immediately.</p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li><strong>Nigeria:</strong> Call 112 or 199 (NCDC Mental Health Support Line)</li>
                <li><strong>United States:</strong> Call or text 988 (Suicide & Crisis Lifeline)</li>
                <li><strong>United Kingdom:</strong> Call 111 or 999 in emergencies</li>
                <li><strong>International:</strong> Contact your local crisis helpline</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">AI Limitations</h2>
              <ul className="list-disc pl-6 space-y-2">
                <li>AI responses are generated by machine learning models and may contain errors, inaccuracies, or inappropriate content.</li>
                <li>Nebiah may not fully understand complex mental health situations or cultural nuances.</li>
                <li>You should always use your judgment and seek professional help when needed.</li>
                <li>Do not rely solely on AI-generated advice for important health decisions.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">Privacy and Data</h2>
              <p>While we take data security seriously, conversations with Nebiah are processed by third-party AI services. Do not share sensitive personally identifiable information or details that could compromise your safety. See our <a href="/privacy" className="text-mint hover:underline">Privacy Policy</a> for more information.</p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-gray-900 mb-3">Acceptance of Risk</h2>
              <p>By using Talk2Nebiah, you acknowledge and accept that:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>The service is provided "as is" without warranties of any kind.</li>
                <li>We are not liable for any damages or harm arising from your use of the service.</li>
                <li>You use the service at your own risk.</li>
              </ul>
            </section>
          </div>
        </div>
      </section>
      <Footer />
    </main>
  );
}
